### ISSUE TITLE
What version of flyway-core to use

### ISSUE THREAD

**Issue by trickleup** [olavloite/spanner-flyway-example#1]
Hi,

I'm trying to use this example to implement flyway migrations for spanner, while waiting for official support to be added. 

I'm unable to run the project, however, because the fork of flyway-core is not available through maven/gradle:

https://github.com/olavloite/spanner-flyway-example/blob/e0af075b9bde6a8e42e5d09a28a134a31069497e/pom.xml#L52

What workflow would you recommend to include the flyway fork into this project? Would I manually have to build it and put the jar on the classpath?

Thanks for pushing the spanner support forward - eagerly awaiting it!

**Comment by olavloite** [comment]
Hi @trickleup ,

I have just updated the flyway fork with the last changes from flyway, and this example to the most recent version of the jdbc driver etc. and tested it against the most recent version of my fork. This does work. So what you probably should do is:
1. Checkout my fork in the workspace of the project you are working on (https://github.com/olavloite/flyway)
2. Include the same dependency in your project as the one in the example (i.e. with the version 0-SNAPSHOT). This should create a project dependency in your project for the forked version of flyway.

Another option would be to check out the flyway fork, assign this a version number locally and build it. This is then a version that you could place in your own artifactory or other repository and get it from there.

May I also point you to another project that I have developed, and helps me a lot when developing things for Cloud Spanner: The Cloud Spanner Emulator. It does not try to emulate the scalability of Cloud Spanner, it only tries to emulate its interface, but it is a lot faster when it comes to schema changes. This is especially handy when trying things with something like flyway or other things that need frequent schema changes. Have a look here for how to setup a trial account: https://www.googlecloudspanner.com/2018/07/create-trial-account-for-cloud-spanner.html
