### ISSUE TITLE
How to avoid limitation by number of mutations per commit

### ISSUE THREAD

**Issue by BohdanKorinnyi** [olavloite/spanner-flyway-example#3]
Hi, I am using Flyway `nl.topicus.spanner.flyway:flyway-core:0.1.0`. When I run the following script I get an error about limit of 20K mutations per commit, is there any way to solve the issue?

```
SET_CONNECTION_PROPERTY AsyncDdlOperations=true;
SET_CONNECTION_PROPERTY AutoBatchDdlOperations=true;

UPDATE Users SET Name = LOWER(Name) WHERE Name IS NOT NULL;

EXECUTE_DDL_BATCH;
WAIT_FOR_DDL_OPERATIONS;

RESET_CONNECTION_PROPERTY AsyncDdlOperations;
RESET_CONNECTION_PROPERTY AutoBatchDdlOperations;
```

Thanks

**Comment by olavloite** [comment]
Hi @BohdanKorinnyi 

Yes, you could use the property `AllowExtendedMode`. When this mode is enabled, the driver will try to detect too large updates and break these up into multiple transactions. Please note that this will break the atomicity of the statement, and you could end up with only some of the updates actually having been applied.
The 20K mutations limit is enforced by Spanner, so there is nothing else than this that the driver can do.

Your script would then be:

```SQL
SET_CONNECTION_PROPERTY AsyncDdlOperations=true;
SET_CONNECTION_PROPERTY AutoBatchDdlOperations=true;
SET_CONNECTION_PROPERTY AllowExtendedMode=true;

UPDATE Users SET Name = LOWER(Name) WHERE Name IS NOT NULL;

EXECUTE_DDL_BATCH;
WAIT_FOR_DDL_OPERATIONS;

RESET_CONNECTION_PROPERTY AsyncDdlOperations;
RESET_CONNECTION_PROPERTY AutoBatchDdlOperations;
RESET_CONNECTION_PROPERTY AllowExtendedMode;
```

See the wiki for more information on `AllowExtendedMode`: [https://github.com/olavloite/spanner-jdbc/wiki/URL-and-Connection-Properties](https://github.com/olavloite/spanner-jdbc/wiki/URL-and-Connection-Properties)

Please let me know if this solves your problem.

**Comment by BohdanKorinnyi** [comment]
It solved my problem, thanks!
